### ISSUE TITLE
Prism Uno based on Prism for Xamarin.Forms?

### ISSUE THREAD

**Issue by weitzhandler** [unoplatform/Uno.Prism#10]
Hi,

I think it makes sense to have the Prism Uno based on the  Prism XF rather than on the UWP. Here are a few reasons:

1. The Prism team [has abandoned](https://github.com/PrismLibrary/Prism/issues/1745) UWP support
2. UWP in Prism doesn't provide crucial multi-platform features, such as `IPageDialogService` and others, that are very essential bits in an Uno app.
3. We should at least strive to have the interfaces to open a bleeding edge for devs to write their own implementation on the interfaces, then hopefully PR.

**Comment by jeromelaban** [comment]
This repository is now archived, for information about Uno support please [visit the official Prism repository](https://github.com/PrismLibrary/Prism).
