### ISSUE TITLE
[Question/Enhancement] WinUI 3 - current state

### ISSUE THREAD

**Issue by tomasfabian** [unoplatform/Uno.Prism#15]
Are there any plans to add [WinUI 3](https://github.com/microsoft/microsoft-ui-xaml/blob/master/docs/roadmap.md#winui-3) support for PRISM? 
In this article Uno team announced [Uno Platform 3.0 – Support for WinUI 3.0 Preview 1](https://platform.uno/blog/announcing-uno-platform-3-0-support-for-winui-3-0-preview-1/). 

I found this [PR](https://github.com/PrismLibrary/Prism/pull/2054) from @jeromelaban approved by @dansiegel and it's announcement [UWP, WinUI and UNO PRISM support](https://platform.uno/blog/uwp-winui-and-uno-platform-get-prism-support-thanks-to-uno-team-oss-contribution/).
At first I tried to use [Prism.Uno 8.0.0.1740-pre] in a [Blank App, Packaged (WinUI in Desktop) app template](https://marketplace.visualstudio.com/items?itemName=Microsoft-WinUI.WinUIProjectTemplates) (it is without the *.Shared project contained in Uno templates).

```C#
    protected override Windows.UI.Xaml.UIElement CreateShell()
    {      
      Microsoft.UI.Xaml.UIElement shell = new Shell();

      //Cannot implicitly convert type 'Microsoft.UI.Xaml.UIElement' to 'Windows.UI.Xaml.UIElement'	
      return shell;
    }
```
Prism.Uno uses **Windows.UI.Xaml** namespace instead of **Microsoft.UI.Xaml**, so I suppose it is only for WinUI 2 now.

It would be nice to have WinUI 3 (Win32 - WPF, WinForms etc. / UWP) support for PRISM, too. 

Thank you
Regards tomasfabian

**Comment by jeromelaban** [comment]
Indeed, the support for WinUI 3 is not there yet. The support for the WinUI 3 API in Uno is still in preview (Uno 3.0) but should be available soon.

This also means that there will be at least one more package for WinUI 3.0, most likely called `Prism.Uno.WinUI` or something similar.

**Comment by ThomasDallmeier** [comment]
Anything new for WinUI 3 support?

**Comment by jeromelaban** [comment]
Not yet, we're expecting some changes (probably breaking) in the next WinUI preview, so to avoid having to build changes, we're waiting a bit.

**Comment by ThomasDallmeier** [comment]
> Not yet, we're expecting some changes (probably breaking) in the next WinUI preview, so to avoid having to build changes, we're waiting a bit.

thank you

**Comment by sigmarsson** [comment]
Hi

Is WinUi3 preview 3 capable to incorporate with with Prism/Uno?

**Comment by jeromelaban** [comment]
We're making progress on WinUI 3 compatibility, stay tuned.

**Comment by inamdarchaitanya** [comment]
Any expected date for this compatibility ?

**Comment by Aloento** [comment]
Is there any new progress?

**Comment by sigmarsson** [comment]
@Aloento , not aware of any. you can try whether it is feasible to reproduce [these](https://stackoverflow.com/questions/66572508/how-to-incorporate-win-ui-with-prism-across-the-uno-platform?noredirect=1#comment117685298_66572508) steps on your desktop.

**Comment by dansiegel** [comment]
I would suggest for all on this thread.... let's move this to the [Prism Discussions](https://github.com/PrismLibrary/Prism/discussions)

**Comment by jeromelaban** [comment]
This repository is now archived, for information about Uno support please [visit the official Prism repository](https://github.com/PrismLibrary/Prism).
