### ISSUE TITLE
[Bug] Documentation points to nonexistent folder

### ISSUE THREAD

**Issue by chingucoding** [unoplatform/Uno.Prism#17]
The readme points to this link: https://github.com/unoplatform/Uno.Prism/tree/master/Sandbox/Uno/HelloWorld

However that doesn't seem to exist anymore, GitHub is reporting a 404 for this URL.

**Comment by jeromelaban** [comment]
This repository is now archived, for information about Uno support please [visit the official Prism repository](https://github.com/PrismLibrary/Prism).
