### ISSUE TITLE
Visual Studio Uno.Prism templates

### ISSUE THREAD

**Issue by weitzhandler** [unoplatform/Uno.Prism#6]
Hi,

The current Prism projects are neat but:

- Rely on the actual project references (not on Uno.Prism from NuGet)
- Are not offered as a VS project template

Please have issue #5 fixed, then expand the Uno templates extension to include the Prism projects.

Thank you!

**Comment by jeromelaban** [comment]
This repository is now archived, for information about Uno support please [visit the official Prism repository](https://github.com/PrismLibrary/Prism).
