### ISSUE TITLE
SessionStateServiceException exceptions

### ISSUE THREAD

**Issue by HaoLife** [unoplatform/Uno.Prism#7]
### Description
When Android switches Activity, an invalid storage interface in SessionStateService causes a program crash problem.
Methods used to DataProtectionProvider storage are not implemented in Uno

At this point, we must register with the new SessionStateService service to the IOC, replacing the implementation method

### Steps to Reproduce

1. Install Xam.Plugin.Media on Android (Install-Package Xam.Plugin.Media -Version 4.0.1.5)
2. Execute the selection file ( await CrossMedia.Current.PickPhotoAsync)
3. SessionStateService execution SaveAsync appears SessionStateServiceException  

### Basic Information

- Version with issue: Uno.Prism.Autofac.Windows -Version 7.1.0-pre.4

**Comment by jeromelaban** [comment]
This repository is now archived, for information about Uno support please [visit the official Prism repository](https://github.com/PrismLibrary/Prism).
